In [2]:
import sqlite3
import pandas as pd
import numpy as np
from helper_functions import *

In [3]:
conn=sqlite3.connect('data/churn.db')
cur=conn.cursor()

In [4]:
LTV=pd.read_sql('SELECT CustomerID,TotalCharges FROM churn_all;',conn)
#LTV['TotalCharges']=LTV['TotalCharges'].apply(convert2float)

# Transforming pandas dataframe to a dictionary
LTV_dict=LTV.set_index('CustomerID').T.to_dict('records')[0]

sorted_customer_dict=bubble_sort_dict(LTV_dict,desc=True)

In [5]:
# Tagging customers as high and low value
churn_df=pd.read_sql('SELECT * from churn_all;',conn)
churn_df['TotalCharges']=churn_df['TotalCharges'].apply(convert2float)

thresh_val=churn_df.TotalCharges.quantile(0.8)
churn_df['is_highVal']=churn_df['TotalCharges'].apply(lambda x:1 if x>thresh_val else 0)

In [6]:
churn_df.head()

,CustomerID,Gender,SeniorCitizen,Partner,Dependents,Tenure,Contract,PaymentMethod,PaperlessBilling,MonthlyCharges,...,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,is_highVal
0,3668-QPYBK,Male,No,No,No,2,Month-to-month,Mailed check,Yes,53.85,...,Yes,No,DSL,Yes,Yes,No,No,No,No,0
1,9237-HQITU,Female,No,No,Yes,2,Month-to-month,Electronic check,Yes,70.70,...,Yes,No,Fiber optic,No,No,No,No,No,No,0
2,9305-CDSKC,Female,No,No,Yes,8,Month-to-month,Electronic check,Yes,99.65,...,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,0
3,7892-POOKP,Female,No,Yes,Yes,28,Month-to-month,Electronic check,Yes,104.80,...,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,0
4,0280-XJGEX,Male,No,No,Yes,49,Month-to-month,Bank transfer (automatic),Yes,103.70,...,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,1

In [7]:
#churn_df['ZipCode'].nunique()
churn_df.columns

Index(['CustomerID', 'Gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'Tenure', 'Contract', 'PaymentMethod', 'PaperlessBilling',
       'MonthlyCharges', 'TotalCharges', 'Churn', 'State', 'Latitude',
       'Longitude', 'ZipCode', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'is_highVal'],
      dtype='object')

In [8]:
# of customers who churned,what percentage do not have dependents
churn_df[churn_df['Churn']=='Yes']['Dependents'].value_counts(normalize=True)

No     0.943285
Yes    0.056715
Name: Dependents, dtype: float64

In [9]:
conn.close()